### ISSUE TITLE
似乎对中文不起作用

### ISSUE THREAD

**Issue by ivaquero** [flaribbit/indenta#3]

**Comment by flaribbit** [comment]
看看代码）

**Comment by flaribbit** [comment]
我猜标题后面没空行

标题后面需要有个空行，故意这样设计的，代码上能统一一些）

**Comment by ivaquero** [comment]
欧了。不过，希望在 box 里面也能加入这个功能

**Comment by black-desk** [comment]
> 我猜标题后面没空行
> 
> 标题后面需要有个空行，故意这样设计的，代码上能统一一些）

不过 为什么呢？可以稍微解释一下么？

以及就 如果可以加个参数让我可以关掉这个检查就好了。

**Comment by flaribbit** [comment]
偷懒了。

正如你看到的，这个包基于状态机实现。为了简化逻辑，把 heading 和公式当成了同一种东西。

如果 heading 后面不需要空行而公式后面需要空行，那要增加一些状态和转移了，想想都麻烦
