### ISSUE TITLE
对于以引号开头的段落无效

### ISSUE THREAD

**Issue by Asta-QQ** [flaribbit/indenta#5]
如果某一段是以引号 (") 开头的话，会不起作用。

**Comment by flaribbit** [comment]
我趣！太魔法了！

**Comment by Asta-QQ** [comment]
> 我趣！太魔法了！

哈哈哈，刚才搞了半天发现不起作用，最后好不容易才发现是因为开头有个引号。

感谢大佬的包，等这么个包好久了。顺便想问一下有没有推广到适用box内的段落的计划。

**Comment by flaribbit** [comment]
我觉得 box 内写段落不太符合逻辑，block 内还差不多。

之后可能考虑加个开启递归的选项。

---

原因定位到了，发现还有一堆没考虑到的行内元素：https://typst.app/docs/reference/text/smartquote/

---

应急的话，可以试一下使用 `#show: fix-indent(unsafe: true)`，关掉行内元素的检查。

或者使用 `fakepar` 方案

```typst
#let fakepar=context{box();v(-measure(block()+block()).height)}
#show heading: it=>it+fakepar
#show figure: it=>it+fakepar
// ...
```
