### ISSUE TITLE
Wrong indentation when the first element is elem/strong

### ISSUE THREAD

**Issue by Coekjan** [flaribbit/indenta#9]
```typ
#import "@preview/indenta:0.0.3": fix-indent

#set par(first-line-indent: 2em)
#show: fix-indent()

= A

B // Looks Good!

= C

_D_  // Error Here

= E

*F* // Error Here
```

![image](https://github.com/flaribbit/indenta/assets/69834864/ff3da60c-930b-4b56-add3-208d1060050e)

**Comment by flaribbit** [comment]
Thanks for your feedback. Seems that there are still many inline elements missed. I will add them later.

You can use `fix-indent(unsafe: true)` to disable the inline check for now.

**Comment by Coekjan** [comment]
Thanks for your reply. Hope this package goes better.

And I am still wondering **why** the `unsafe` option is _unsafe_ :no_mouth:

**Comment by flaribbit** [comment]
This package works by adding an `h(indent-length)` after a specific element (denoted as *a*) and before the first paragraph after it (denoted as *b*).

But there is no good way to tell if *b* is a paragraph or an inline element. **If an `h(indent-length)` is added before a block element, it will result in an extra blank line.**

The current practice is to be **more conservative by default**, determining that *b* is 1) not a block element and is 2) in the list of known inline elements.

The list is currently not perfect. By specifying `unsafe: true`, the 2) inline element check can be skipped.
